Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-24.04"

  config.vm.define "vm1" do |vm1|
    vm1.vm.synced_folder ".", "/vagrant"
  end

  
  config.vm.define "vm2" do |vm2|
    vm2.vm.network "private_network", ip: "192.168.33.10"
    vm2.vm.synced_folder ".", "/vagrant"
  end

  
  config.vm.define "vm3" do |vm3|
    vm3.vm.network "public_network", ip: "192.168.1.100"
    vm3.vm.synced_folder ".", "/vagrant"
  end
end
